baseURL = 'https://mankoo.ca'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'

[Params]
    mainSections = ["posts"]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/smankoo"
    twitter = "https://twitter.com/XXX"
    email = "sumeet@mankoo.ca"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    posts = "/:filename/"


